#! /bin/sh

read -p "Full git project repo url: " project

# Set up submodule properly
git submodule init
git submodule update

# Install Node tools in the right dir
cd tools
npm install express
cd ../

# New project sets up git properly
if [ ! $project = "" ]; then
  git remote rm origin
  git remote add origin $project

  git rm install  
  git commit -m "Initial Commit into $project"
fi
